import Head from 'next/head';
import { MapProvider } from 'react-map-gl';

import { TNextPageWithLayout } from 'types';
import { Esri } from '@/features';

const EsriPage: TNextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Esri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-screen h-screen">
        <MapProvider>
          <Esri />
        </MapProvider>
      </main>
    </>
  );
};

EsriPage.layout = 'main';

export default EsriPage;
