import Head from 'next/head';

import { TNextPageWithLayout } from 'types';

const MapboxPage: TNextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Mapbox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Mapbox Page</h1>
    </>
  );
};

MapboxPage.layout = 'main';

export default MapboxPage;
